#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: ' Koffer | Artifact Rake Utility' 
  hosts: local
  vars_files:
    - vars/global.yml

- name: 'Koffer | Artifact Rake Utility | import_playbook | auth.yml'
  import_playbook: auth.yml

- name: 'Koffer | Artifact Rake Utility | import_playbook | images.yml'
  import_playbook: images.yml

- name: 'Koffer | Artifact Rake Utility | import_playbook | bundle.yml'
  import_playbook: bundle.yml
