---
- name: '{{ ansible_name_module }} | command:wall-e | Building catalog & Mirroring with wall-e opm wrapper | CREDIT: @arvin-a https://github.com/arvin-a/openshift-disconnected-operators'
  shell:
    chdir: "/root/koffer/collector/roles/wall-e/tasks"
    cmd: |
      REGISTRY_AUTH_FILE='/root/.docker/config.json' PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /bin/wall-e --output /tmp/koffer/operators/custom-redhat-operator-index-manifests --operator-file ./custom-offline-operator-list --authfile /root/.docker/config.json --registry-catalog localhost:5000 --registry-olm localhost:5000 --catalog-version 1.0.0 --icsp-scope=namespace --opm-path /usr/bin/opm --run-dir /root/koffer/collector/roles/wall-e/tasks/
