apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-imagestream-config-map
data:
  registry.tacobell.besttacos.com..5000: | 
    -----BEGIN CERTIFICATE-----
    MIIFfDCCA2SgAwIBAgIUV6nQWKptjGCIqE6MpJ09sujOb1wwDQYJKoZIhvcNAQEL
    BQAwITEfMB0GA1UEAwwWdGFjb2JlbGwuYmVzdHRhY29zLmNvbTAeFw0yMDA3MjMx
    ODAyNDVaFw0zMDA3MjExODAyNDVaMCExHzAdBgNVBAMMFnRhY29iZWxsLmJlc3R0
    YWNvcy5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCheiJvj5sW
    9Ff2w6TvN2aSnLHhwHjT5aYaWc+OFhJdXHWNxdT/+kCs3AoK7JxJtr/PXqoCuq2w
    Vg1sa63W53RGGfjN0l2XMVelS5RmEYt1pf+pPHYSSPBGUXc6rCtJITtDRGYERhb2
    +2c+Tf5BBU4P5EFhaBkb2XXvCx6D0PU+nz60iQj/C5lOENFnBCxwKrWkfLGM4PTt
    szS7kp+miGparvwzJVybJzoqMlZQS4uS/e3l+AZmuvi5GbILlx3hqvz98iaEgoyS
    8wDHh5VroKXoRn1RWqwzc6np7/suogVR8E69zNZ2j4phqv0blUhDiClq4zdnhJWn
    rMQN23vCiIc+6chDSn5KOZ2mIxRzX2+5hN1WMnvX2lY7vC901fZ5dZfFJReyEkXh
    EqEcr4jkBWOWQbXDHf9FeN2UXiXVN5X9eFbthcyh0tK/2vHL4CeKTIxmx2wwsESe
    5dFUYN5qkoHjmGMQfqZ0SxjMwPXxfYadXQWl8ltDfY2vfL4j4RhAZRSjQhMweoSz
    kIjrEcs8qG9hLmpUk7sTDaI24hNjPmR0CrQrXdHcVwrGnTJOKBvTNIR8vVZNfloy
    p9s5nQmsBui+Yn0rZKpI5VteE9nJXS6/tLN8mb1ODzjZ44JiA9cuZJuBJJ4ENQ7m
    e71Q/Qi7AUztOxJ0YWGpZPFjZRnyDnXgJQIDAQABo4GrMIGoMB0GA1UdDgQWBBSi
    m5Voq/E6xjoXCCDddpZJpd/M9zAfBgNVHSMEGDAWgBSim5Voq/E6xjoXCCDddpZJ
    pd/M9zAPBgNVHRMBAf8EBTADAQH/MFUGA1UdEQROMEyCH3JlZ2lzdHJ5LnRhY29i
    ZWxsLmJlc3R0YWNvcy5jb22CCGNsb3VkY3RsgghyZWdpc3RyeYIJbG9jYWxob3N0
    hwQKWAABhwR/AAABMA0GCSqGSIb3DQEBCwUAA4ICAQA/I6P6+Nd1EcEkAzXdUAaE
    Ht4+H37cgOGtr24to/Y3g69uqquGKgPfx0c745M+Lk35AwwvvEemAmq8Kup8vZrB
    MJA4R9eLKhOIfUicu/4FZSVri1F+TIKDPTogJMMUSah3efxB1uOCgrH6eE2kpjVF
    sGHR3LSeyBLbW4aTyWx2IJVEax2uzknNBT7BkQ1R3ZqT3ujBOFtQFTVsGmhV5ETI
    z3noHSKk6e1OsvJT2pFiBaXP+Pq9Xk0uq7Ha7NELJv0beDQaDylddLiEOV0/UB0m
    m7L7CpUfLcu+im1r8Xy2gdGctxWBuOxiTSaw5BWorM8/wzMmEIvAnYW45ae+dnQO
    KRdQX3K9Qs9cz3hKqn2ZhZKEGD1mmGyl9fiGAwd7y4BPcsCLWpgjxtxBOqavDLqo
    5+Pqb/XgfmTE7nDGwBxRzMcwI3lzlKCMk2UGUmTfqCQ+YrTMNnDU3YnPyrej5UGv
    Revadi70FbkeSm7jV8s/XygWErwUnqSfXYh0+N86Y6B4We2gv/CHnYdQ1KHC5hHc
    NZLoXrgCBOHbeRWuztuG4yMh8rKR14VQINM9bwFgHXx6b9GjO9V4i4YJLzyD5Kfz
    TELdsAU/xVNJLiu/qBthLHOsfz4ifumTettCcDVBfND+C1y4poGVEFKdVGthY80p
    PjVBZ3b/rm1Hrkikb/3hIg==
    -----END CERTIFICATE-----
