apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Operators
  image: registry.tacobell.besttacos.com:5000/redhat-operators:1.0.0
  imagePullPolicy: Always
  publisher: Red Hat
  sourceType: grpc