#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | bundle.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "bundle"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    redhat_quay_pull_file: '{{ dir_artifacts }}/.docker/master.json }}'
  tasks:
    - name: '{{ ansible_name_module }} | file:absent | Purge pre-existing operator bundles'
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ dir_bundle }}/koffer-bundle.collector-operators.tar'
        - '{{ dir_bundle }}/koffer-bundle.collector-operators.tar.sha256'
    
    - name: '{{ ansible_name_module }} | command:tar | build tarball bundle of all artifacts'
      command:
        "tar -cv -f {{ dir_bundle }}/koffer-bundle.collector-operators.tar -C {{ local_home }} platform"
      args:
        creates: '{{ dir_bundle }}/koffer-bundle.collector-operators.tar'
        warn: false
    
    - name: '{{ ansible_name_module }} | stat:sha256 | SHA koffer-bundle.collector-operators.tar'
      command: 'sha256sum koffer-bundle.collector-operators.tar'
      args:
        warn: false
        chdir: '{{ local_home }}/bundle'
      register: bundle_sha
    
    - name: '{{ ansible_name_module }} | copy:content.sha256 | Create Sha256 Verification file'
      copy:
        content: '{{ bundle_sha.stdout }}'
        dest: '{{ local_home }}/bundle/koffer-bundle.collector-operators.tar.sha256'
