---
koffer:
  walle: "{{    lookup('env', 'WALLE')       | default('true',  true) | bool }}"
  mirror: "{{   lookup('env', 'MIRROR')      | default('false', true) | bool }}"
  bundle: "{{   lookup('env', 'BUNDLE')      | default('false', true) | bool }}"
  omnibus: "{{  lookup('env', 'OMNIBUS')     | default('false', true) | bool }}"
  manifest: "{{ lookup('env', 'MANIFEST')    | default('true',  true) | bool }}"
  date: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}"
  docker_config: '/root/.docker/config.json'
  plugin: 'operators'

catalog:
  release: "{{ lookup('env', 'VERSION')        | default('latest',         true) }}"
  dest: "{{    lookup('env', 'CATALOG_MIRROR') | default('localhost:5000', true) }}"

operators:
  redhat:
    id: 1
    list: "{{ lookup('env',  'REDHAT_OPERATORS') | default('null', true) }}"
    image: "{{ lookup('env', 'REDHAT_CATALOG')   | default('registry.redhat.io/redhat/redhat-operator-index:v4.7', true) }}"
  certified:
    id: 2
    list: "{{ lookup('env',  'CERTIFIED_OPERATORS') | default('null', true) }}"
    image: "{{ lookup('env', 'CERTIFIED_CATALOG')   | default('registry.redhat.io/redhat/certified-operator-index:v4.7', true) }}"
  community:
    id: 3
    list: "{{ lookup('env', 'COMMUNITY_OPERATORS') | default('null', true) }}"
    image: "{{ lookup('env', 'COMMUNITY_CATALOG')  | default('registry.redhat.io/redhat/community-operator-index:latest', true) }}"
  marketplace:
    id: 4
    list: "{{ lookup('env', 'MARKET_OPERATORS') | default('null', true) }}"
    image: "{{ lookup('env', 'MARKET_CATALOG')  | default('registry.redhat.io/redhat/redhat-marketplace-index:v4.7', true) }}"

dir:
  bin: '/bin'
  tmp: '/tmp/koffer'
  mirror: '/root/platform/mirror'
  koffer: '/root/koffer'
  bundle: '/root/bundle'
  iac: '/root/platform/iac'
  platform: '/root/platform'
  secrets: '/root/platform/secrets'
plugin:
  name: "Koffer Artifact Collector | Red Hat Consulting | CodeSparta/collector-operators"
