---
- name: '{{ plugin.name }} | copy:catalog-source-template | Stage catalog subscription template'
  copy:
    src: 'catalog-source-template'
    dest: '{{ dir.tmp }}/catalog-source-template'
    mode: '0744'
  with_dict:
    - "{{ operators }}"
  when:
    - item.key is defined and item.key != ""
    - item.value.list is defined and item.value.list != "null" and item.value.list != ""
    - item.value.image is defined and item.value.image != ""
    - item.value.id is defined and item.value.id|int > 0

- name: '{{ plugin.name }} | copy:image-content-source-template | Stage imageContentSourcePolicy template'
  copy:
    src: 'image-content-source-template'
    dest: '{{ dir.tmp }}/image-content-source-template'
    mode: '0744'
  with_dict:
    - "{{ operators }}"
  when:
    - item.key is defined and item.key != ""
    - item.value.list is defined and item.value.list != "null" and item.value.list != ""
    - item.value.image is defined and item.value.image != ""
    - item.value.id is defined and item.value.id|int > 0

- name: '{{ plugin.name }} | copy:known-bad-images | Stage known-bad-images file'
  copy:
    src: 'known-bad-images'
    dest: '{{ dir.tmp }}/known-bad-images'
    mode: '0744'
  with_dict:
    - "{{ operators }}"
  when:
    - item.key is defined and item.key != ""
    - item.value.list is defined and item.value.list != "null" and item.value.list != ""
    - item.value.image is defined and item.value.image != ""
    - item.value.id is defined and item.value.id|int > 0
