#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | bundle.yml' 
  hosts: koffer

  vars_files:
    - 'vars/global.yml'

  vars:
    module: "bundle"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: '{{ ansible_name }} | file | Purge pre-existing bundles'
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ dir_bundle }}/{{ bundle_name }}'
        - '{{ dir_bundle }}/{{ bundle_name }}.sha256'
      when: clean_purge_artifacts == True

    - name: '{{ ansible_name }} | copy | Place iCSP and Catalog Subscription file'
      copy:
        src: '{{ local_tmp }}/operators/custom-redhat-operator-index-manifests'
        dest: '{{ dir_platform }}/mirror/operators/'
        remote_src: no
        mode: '0775'

    - name: '{{ ansible_name_module }} | command:tar | Build Artifacts Bundle'
      command:
        cmd: |
          tar -cv --use-compress-program='pigz -9' -f {{ dir_bundle }}/{{ bundle_name }} -C {{ local_home }} platform
      args:
        creates: "{{ dir_bundle }}/{{ bundle_name }}"
    
    ####### SHA256sum Artifact Bundle File
    - name: '{{ ansible_name_module }} | stat:sha256 | SHA ArtifactsBundle.tar.xz'
      command: 'sha256sum {{ bundle_name }}' 
      args:
        chdir: '{{ dir_bundle }}'
      register: bundle_sha
    
    ####### SHA256sum ArtifactsBundle.tar.xz
    - name: '{{ ansible_name_module }} | copy:content.bundle_sha | Place SHA256 SUM File | {{ bundle_sha.stdout }}'
      copy:
        content: '{{ bundle_sha.stdout }}'
        dest: "{{ dir_bundle }}/{{ bundle_name }}.sha256"
        mode: 0777

    - name: '{{ ansible_name_module }} | file:directory | Set Permissions on Bundle'
      file:
        recurse: true
        path: '{{ item }}'
        state: directory
        mode: 0777
      loop:
        - "{{ dir_bundle }}"
