#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: host
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "catalog"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    ####### Copy binaries onto host for execution
    - name: '{{ ansible_name_module }} | copy:/bin/{items} | Place temporary opm binary on host /root/opm'
      copy:
        src: '{{ item.bin }}'
        dest: '{{ item.dest }}'
        mode: '{{ item.mode }}'
      with_items:
        - { bin: '/bin/opm', mode: '0744', dest: '{{ dir_bin }}/opm' }

      ######### Mirror Images to directory
    - name: '{{ ansible_name_module }} | command:cmd_opm | Test OPM Binary'
      command:
        cmd: '{{ item.bin }} {{ item.exec }}'
      with_items:
        - { bin: '{{ dir_bin }}/opm', exec: 'version' }




    ###### Evaluate lock file presence
#   - name: '{{ ansible_name_module }} | stat | check for mirror v2.sha256 Lock file'
#     stat:
#       path: '{{ dir_platform }}/mirror/ocp-release.{{ version_openshift }}.lock'
#     register: mirror_lock_check
    
    ###### Download OpenShift Docker Images from Quay.io to File: /root/platform/mirror/v2
#   - name: '{{ ansible_name_module }} | block | Download OpenShift images'
#     block:
#   
      ######### Purge & Prepare
#       - name: '{{ ansible_name_module }} | file:directory | Create mirror artifact directories'
#         file:
#           path: "{{ dir_platform }}/mirror"
#           state: directory
    
      ####### Place OpenShift RHCOS AWS VMDK
#       - name: '{{ ansible_name_module }} | get_url:url | Place OpenShift RHCOS Image | rhcos-aws.x86_64.vmdk.gz'
#         get_url:
#           url: 'https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/latest/rhcos-aws.x86_64.vmdk.gz'
#           dest: '{{ dir_platform }}/nginx/rhcos'
#           mode: 0775
    
      ######### Mirror Images to directory
#       - name: '{{ ansible_name_module }} | shell:oc.adm.release.mirror | Sync content from quay.io'
#         shell: |
#           {{ dir_bin }}/oc adm release mirror --insecure=true \
#             --to=localhost:5000/openshift-release-dev \
#             --registry-config=/root/.docker/config.json \
#             --from=quay.io/openshift-release-dev/ocp-release:{{ version_openshift }}-x86_64 \
#             --to-release-image=localhost:5000/openshift-release-dev:{{ version_openshift }}-x86_64
#         when: image_mirror_utility == "oc"
     
      ######### Skopeo Copy Images to Registry
#       - name: '{{ ansible_name_module }} | shell:skopeo.copy | Sync content from quay.io'
#         shell: |
#             for i in $(cat /var/lib/koffer/release.list); do \
#               skopeo copy docker://quay.io/$i \
#               docker://localhost:5000/openshift-release-dev/$i ; \
#             done
#         when: image_mirror_utility == "skopeo"
#   
      ####### Block Conditionals
#     when: not mirror_lock_check.stat.exists
    
#   - name: '{{ ansible_name_module }} | command:touch | Place mirror lock file'
#     command:
#       cmd: 'touch {{ dir_platform }}/mirror/ocp-release.{{ version_openshift }}.lock'
#     args:
#       warn: false
