#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml'
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "catalog"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: '{{ ansible_name_module }} | Create Operators list'
      ansible.builtin.template:
        src: templates/operators.j2
        dest: roles/wall-e/custom-offline-operator-list

    - name: '{{ ansible_name_module }} | file:absent | Purge artifact directory custom-{{ index_name }}-manifests'
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ local_tmp }}/operators/custom-{{ index_name }}-manifests'

    - name: '{{ ansible_name_module }} | command:cmd | Podman Pull {{ opm_index_image }}'
      command:
        cmd: |
          podman pull {{ opm_index_image }}

    - name: '{{ ansible_name_module }} | command:cmd | Build Custom Catalog | {{ opm_index_list }}'
      shell:
        chdir: '{{ local_tmp }}/operators'
        cmd: |
          opm index prune --tag {{ index_image_out }} --packages {{ operator_list }} --from-index {{ opm_index_image }}

    - name: '{{ ansible_name_module }} | command:cmd | Push Custom Catalog {{ index_image_out }}'
      shell:
        cmd: |
          podman push --tls-verify=false {{ index_image_out }}

    ## Cannot filter by os arch due to bug:
    ## https://bugzilla.redhat.com/show_bug.cgi?id=1890951
    ## https://github.com/openshift/openshift-docs/pull/27855
    ##    oc adm catalog mirror --insecure --manifests-only --filter-by-os='.*' {{ index_image_out }} {{ target_registry }}
    - name: '{{ ansible_name_module }} | command:cmd | Build Image Mirror Manifests'
      shell:
        chdir: '{{ local_tmp }}/operators'
        cmd: |
          oc adm catalog mirror --insecure --manifests-only --index-filter-by-os='.*' {{ index_image_out }} {{ target_registry }}

    - name: '{{ ansible_name_module }} | find:/tmp/koffer/operators/* | Find index manifests'
      find:
        paths: '{{ local_tmp }}/operators'
        file_type: directory
        recurse: false
        patterns:
          - '*-{{ index_name }}-*'
      register: manifest_dir

    - name: '{{ ansible_name_module }} | copy:mirror.list | Template mirror.list'
      copy:
        src: '{{ item }}/mapping.txt'
        dest: '{{ item }}/mirror.list'
        mode: '0775'
      with_items:
        - "{{ manifest_dir.files[0].path }}"

    - name: '{{ ansible_name_module }} | replace | Format mirror.list'
      replace:
        path: '{{ item }}/mirror.list'
        regexp: '=.*$'
      with_items:
        - "{{ manifest_dir.files[0].path }}"

    - name: '{{ ansible_name_module }} | absent | Remove garbage index build material'
      file:
        path: '{{ local_tmp }}/operators/index*'
        state: absent

    - name: '{{ ansible_name_module }} | copy:/tmp/koffer/operators | Stage Operator imageContentSourcePolicy, mapping.txt'
      copy:
        mode: 0777
        src: '{{ local_tmp }}/operators'
        dest: '{{ dir_platform }}'
      when: bundle == 'true'
