#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "dependencies"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: "{{ ansible_name_module }} | shell:curl_release.txt | Lookup Latest OCP Release"
      shell: curl --silent https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt | awk '/  Version/{print $2}'
      register: openshift_version_latest
      when: openshift_version is not defined

    - set_fact:
        openshift_version: '{{ openshift_version_latest.stdout }}'
        cacheable: yes
      when: openshift_version is not defined

    - name: "{{ ansible_name_module }} | get_url:openshift-client-linux.tar.gz | Downloading OC Client {{ openshift_version }}"
      command:
        cmd: |
          tar xvf /tmp/openshift-client-linux.tar.gz -C /bin/
#      get_url:
#        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-client-linux.tar.gz"
#        dest: '/tmp/openshift-client-linux.tar.gz'
#        mode: '0744'

    - name: "{{ ansible_name_module }} | unarchive:openshift-client-linux.tar.gz | Extracting OC Client {{ openshift_version }}"
      unarchive:
        src: '/tmp/openshift-client-linux.tar.gz'
        dest: '/bin'
        mode: 0775

    - name: '{{ ansible_name_module }} | command:cmd | Test Binaries'
      command:
        cmd: '{{ item.bin }} {{ item.exec }}'
      with_items:
        - { bin: '/bin/oc',  exec: 'version --client' }
        - { bin: '/bin/opm', exec: 'version' }
