#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | git.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
    - 'vars/git.yml'
  vars:
    module: "git"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - git
