#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "mirror"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: '{{ ansible_name_module }} | command:cmd | Mirror Catalog Images | {{ target_registry }}'
      command: |
        oc adm catalog mirror --insecure --filter-by-os='linux/amd64' --registry-config='/root/.docker/config.json' {{ index_image_out }} {{ target_registry }}
