#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | secrets.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "secrets"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | file:directory | Create Docker Pull Secrets Directory'
      file:
        path: "{{ dir_secrets }}/docker"
        state: directory

    - name: '{{ ansible_name_module }} | copy | Save Quay.io Pull Secret to {{ dir_secrets }}/docker/quay.json'
      copy:
        src: "/root/.docker/config.json"
        dest: "{{ dir_secrets }}/docker/quay.json"
        mode: 0600
