#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: 'Koffer | Artifact Rake Utility' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

- import_playbook: tree.yml          # Create required directory tree
- import_playbook: dependencies.yml  # Pull OpenShift oc, openshift-install, and kubectl binaries 
- import_playbook: catalog.yml       # 
- import_playbook: mirror.yml        # Download OCP Infra Container Images
  when: mirror or bundle == 'true'

- import_playbook: bundle.yml       # Bundle artifacts for airgap pivot
  when: bundle == 'true'
