#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: ' Koffer | Artifact Rake Utility' 
  hosts: koffer
  vars_files:
    - vars/global.yml

- name: 'Koffer | Artifact Rake Utility | import_playbook | images.yml'
  import_playbook: images.yml

- name: 'Koffer | Artifact Rake Utility | import_playbook | bundle.yml'
  import_playbook: bundle.yml
