#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | images.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'

  vars:
    module: "images"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: "{{ ansible_name_module }} | shell:curl_release.txt | Lookup Latest OCP Release"
      shell: curl --silent https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt | awk '/  Version/{print $2}'
      register: version_openshift_latest

    - name: "{{ ansible_name_module }} | unarchive:openshift-client-linux.tar.gz | Downloading OC Client Version {{ ocp_version_override | default(version_openshift_latest.stdout) }}"
      unarchive:
        src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version_override | default(version_openshift_latest.stdout) }}/openshift-client-linux.tar.gz"
        dest: '/bin'
        remote_src: yes
        mode: 0775
