#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | tree.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "tree"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  tasks:

    - name: '{{ ansible_name_module }} | file:directory | Create Artifact Directory Tree' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0744'
        recurse: yes
      with_items:
        - '{{ dir_platform }}'
        - '{{ dir_platform }}/mirror'
        - '{{ dir_platform }}/operators'
        - '{{ dir_platform }}/operators/custom-{{ index_name }}-manifests'
        - '{{ local_tmp }}/operators'

    - name: '{{ ansible_name_module }} | file:directory | Create Artifact Directory Tree' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0744'
        recurse: no
      with_items:
        - '{{ local_tmp }}'
        - '{{ local_tmp }}/operators'
      delegate_to: host

    - name: '{{ ansible_name_module }} | file:directory | Set Bundle Directory Permissions' 
      file:
        path: '{{ dir_bundle }}'
        state: directory
        mode: '0777'
        recurse: no
