#!/usr/local/bin/ansible-playbook
- name: '{{ plugin.name }} | Koffer | tree.yml' 
  hosts: koffer
# vars_files:
#   - 'group_vars/koffer.yml'
  vars:
    module: "tree"
    ansible_name_module: "{{ plugin.name }} | {{ module }}"

  tasks:

    - name: '{{ ansible_name_module }} | file:[absent,directory] | Prepare staging directory'
      file:
        path: '{{ dir.tmp }}/operators/custom-operator-manifests'
        state: absent

    - name: '{{ ansible_name_module }} | file:directory | Create Artifact Directory Tree' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0744'
        recurse: no
      with_items:
        - '{{ dir.tmp }}'
#       - '{{ dir.tmp }}/operators/custom-operator-manifests'
#       - '{{ dir.mirror }}'
#       - '{{ dir.platform }}'
