#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | tree.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "tree"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"

  tasks:

    - name: '{{ ansible_name_module }} | file:[absent,directory] | Prepare staging directory'
      file:
        path: '{{ local_tmp }}/operators/custom-{{ index_image_out }}-manifests'
        state: absent

    - name: '{{ ansible_name_module }} | file:directory | Create Artifact Directory Tree' 
      file:
        path: '{{ item }}'
        state: directory
        mode: '0744'
<<<<<<< HEAD
        recurse: no
=======
        recurse: yes
>>>>>>> 873c5f110b08f5706ae5f0d940be10c308e8be3d
      with_items:
        - '{{ dir_platform }}'
        - '{{ dir_platform }}/mirror'
        - '{{ local_tmp }}'
        - '{{ local_tmp }}/operators/custom-{{ index_name }}-manifests'
