#!/usr/local/bin/ansible-playbook --inventory=inventory.yaml
- name: '{{ name_vendor }} | Koffer | wall-e.yml' 
  hosts: koffer
  vars_files:
    - 'vars/global.yml'
  vars:
    module: "wall-e"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
  roles:
    - wall-e
